apiVersion: v1
kind: Service
metadata:
  name: {{ template "spring-boot-chart.fullname" . }}-service
spec:
  type: NodePort
  selector:
    app: {{ template "spring-boot-chart.fullname" . }}-spring-boot-demo
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31845
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "spring-boot-chart.fullname" . }}-deployment
  labels:
    app: {{ template "spring-boot-chart.fullname" . }}-spring-boot-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "spring-boot-chart.fullname" . }}-spring-boot-demo
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "spring-boot-chart.fullname" . }}-spring-boot-demo
    spec:
      containers:
      - name: spring-boot-demo
        image: spring-boot:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: application
          containerPort: 8080
